### PR TITLE
Accumulated Volume wrong type causing unmarshalling errors in the client

### PR DESCRIPTION
**Pull request by antdjohns**
Addressing GH [ticket](https://github.com/polygon-io/client-go/issues/224)

MinuteSnapshot is using the wrong type for the AccumulatedVolume field. A user reported an error with unmarshalling that I was able to reproduce.

### CODE REVIEW

**Comment by nathanhack** [comment]
This would be nice to have.

**Comment by nathanhack** [comment]
That said, the api from polygon.io has the field type set as a `number` (instead of an `integer`) which would imply there exist cases where the volume could be fractional. Is that possible?

**Comment by antdjohns** [comment]
> That said, the api from polygon.io has the field type set as a `number` (instead of an `integer`) which would imply there exist cases where the volume could be fractional. Is that possible?

Yes, stock splits and acquisitions can cause fractional shares.

**Comment by nathanhack** [comment]
> 

Oh good point, I didn't think of either acquisitions or reducing splits. I stand by my, `good to have` position.

**Review by morningvera — APPROVED** [review]
@antdjohns lgtm but can you also change the test? changing this to a float is probably sufficient: https://github.com/polygon-io/client-go/blob/master/rest/snapshot_test.go#L41

**Comment by antdjohns** [comment]
@morningvera @jbonzo updated the test data to use a float; would you like me to merge? and if releasing can I include the version patch update in this pr or cut another pr?

**Comment by morningvera** [comment]
@antdjohns yeah, you can merge it but let’s wait on releasing until tomorrow

**Pull request merged**
